//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace full_curd_operation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class curd
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string hobbies { get; set; }
        public string language { get; set; }
    }
}
